import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./../globals.scss";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "../i18n/routing";
import { Header } from "../components/hearder";
import Footer from "../components/footer";
import { notFound } from "next/navigation";
import localFont from "next/font/local";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const mBFSpaceHabitat = localFont({
  src: [
    {
      path: "../../public/fonts/DFVNMBFSpaceHabitat/MBFSpaceHabitat.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/DFVNMBFSpaceHabitat/MBFSpaceHabitat.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-DFVN-MBF-Space-Habitat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sạc luôn - Dịch vụ cho thuê sạc dự phòng tiện lợi",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={`${montserrat.variable} ${mBFSpaceHabitat.variable} antialiased`}>
      <body>
        <NextIntlClientProvider>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
